C = float(input('Inserte la presion en Kilo Pascales:'))
a = (C*0.145028)
b = (C*7.50062)
c = (C*101.325)
print('libra por pulgada cuadrada:', a)
print('milimetros de mercurio:', b)
print('atmosferas:', c)