pan = float(input('Cantidad de hozagas de pan por dia:'))
hozaga = (3.49)
hozagacondescuento = (1.396)
descuento = (2.094)
a = (pan*hozaga)
b = (pan*descuento)
c = (pan*hozagacondescuento)
print ('Precio regular:                  ',' %.2F' %a)
print ('Descuento:                       ',' %.2F' %b)
print ('Total:                           ',' %.2F' %c)